### ISSUE TITLE
Ejecting Expo

### ISSUE THREAD

**Issue by codeundercoverdev** [creativetimofficial/argon-react-native#10]
I am evaluating the free version with the hopes of buying the paid version.  I will need to be able to eject expo so I am trying to do that with the  free version

# Expected Behavior

After running `expo eject` the app works

# Current Behavior

After running `expo eject` I get the following error:

```
The Expo SDK requires Expo to run. It appears the native Expo modules are unavailable and this code is not running on Expo. Visit https://docs.expo.io to learn more about developing an Expo project.

<unknown>
    validate.fx.js:9:10
loadModuleImplementation
    require.js:331:6
<unknown>
    Expo.fx.js:1
loadModuleImplementation
    require.js:331:6
<unknown>
    ExpoLazy.js:464:7
loadModuleImplementation
    require.js:331:6
<unknown>
    App.js:3
loadModuleImplementation
    require.js:331:6
<unknown>
    index.js:2
loadModuleImplementation
    require.js:331:6
guardedLoadModule
    require.js:197:45
global code
    <unknown file>:0

```

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. `expo eject`
2.  `cd ios`
3.  `pod install`
4.  `cd ../`
5.  `react-native run-ios`

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: IOS 11 Simulator
* Operating System: Mac Mojave

**Comment by palingheorghe** [comment]
Hi @codeundercoverdev ! Thank you for your interest in our product! Every time you're trying to eject an Expo app via `expo eject` the terminal gives you 3 options: 'Bare', 'ExpoKit' and 'Cancel'. 
The first option completely removes Expo while the 2nd version uses ExpoKit. Which one did you choose? 

Alin

**Comment by o-pooja-o** [comment]
> Hi @codeundercoverdev ! Thank you for your interest in our product! Every time you're trying to eject an Expo app via `expo eject` the terminal gives you 3 options: 'Bare', 'ExpoKit' and 'Cancel'.
> The first option completely removes Expo while the 2nd version uses ExpoKit. Which one did you choose?
> 
> Alin

got same issue chose bare from the option

**Comment by palingheorghe** [comment]
@o-pooja-o Hi! You could find more about this error and ejecting Expo here: https://docs.expo.io/versions/latest/bare/using-expo-client/#avoid-importing-the-expo-package-in-bare . This should help you set up your app the way you wanted ❤️

Alin

**Comment by davidecantoni** [comment]
> @o-pooja-o Hi! You could find more about this error and ejecting Expo here: https://docs.expo.io/versions/latest/bare/using-expo-client/#avoid-importing-the-expo-package-in-bare . This should help you set up your app the way you wanted ❤️
> 
> Alin

Fixes the issues on our side too. Search for 'expo' imported modules and remove them.

**Comment by o-pooja-o** [comment]
HELP ME RESOLVE THIS ERROR PLEASE WHICH APPEARS AFTER EJECTING THE EXPO PROJECT.

"TurboModuleRegistry.getEnforcing(...):'AppState' could not be found.Verify that a module by this name is registered in native binary"

**Comment by o-pooja-o** [comment]
> HELP ME RESOLVE THIS ERROR PLEASE WHICH APPEARS AFTER EJECTING THE EXPO PROJECT.
> 
> "TurboModuleRegistry.getEnforcing(...):'AppState' could not be found.Verify that a module by this name is registered in native binary"

@palingheorghe @davidecantoni

**Comment by palingheorghe** [comment]
Hi @o-pooja-o ! Could you please expand on your issue? How can I reproduce it in order to see what kind of solution would best work for you? 

Thanks,
Alin

**Comment by o-pooja-o** [comment]
> Hi @o-pooja-o ! Could you please expand on your issue? How can I reproduce it in order to see what kind of solution would best work for you?
> 
> Thanks,
> Alin

Actually now I know. I had an expo built project, I ejected it to react native 0.61.5, but i still had few expo dependencies, so probably this is why I m not able to start my project  neither with react-native-start nor with expo start. Now I will need to remove every dependencies from the project related to expo and then and only then I can run this project in native environment. But still if you can figure out from what source I am getting this turboModule error then it can be added to my knowledge.
