### ISSUE TITLE
Expo Snack problem with importing files.

### ISSUE THREAD

**Issue by gustawdaniel** [creativetimofficial/argon-react-native#12]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Go to 

> https://snack.expo.io/@maciej.stachowiak/github.com-creativetimofficial-argon-react-native

Run app on phone

I should see no errors 

# Current Behavior

What is the current behavior?

# Failure Information (for bugs)

But I see

```
Did you know:
You can turn off automatic updates under Devices in the footer?
Unable to resolve module 'module://constants/.js'
  Evaluating module://constants/.js
  Evaluating module://screens/Pro.js.js
  Evaluating module://navigation/Screens.js.js
  Evaluating module://App.js.js
  Loading module://App.js
Error: Unable to resolve module 'module://constants/.js'
    at Object.eval (module://constants/.js!transpiled:1:113)
    at eval (module://constants/.js!transpiled:2:4)
    at eval (module://constants/.js!transpiled:3:3)
    at eval (<anonymous>)
    at [snack internals]
    at Object.n ([snack internals]
    at e.evaluate ([snack internals]
    at He ([snack internals]
    at [snack internals]
    at https://snack.expo.io/web-player/35/static/js/app.3571fe13.chunk.js:1:11412
```

![Screenshot from 2020-01-16 10-21-21](https://user-images.githubusercontent.com/16663028/72510565-f573da80-3849-11ea-869b-21f9369aa41d.png)

## Steps to Reproduce

1. On https://snack.expo.io/@maciej.stachowiak/github.com-creativetimofficial-argon-react-native
2. Scan QR code for Android using EXPO android app
3. See red error

## Context

Using

https://demos.creative-tim.com/argon-react-native/docs/#/install

I tried install it on my system

* Ubuntu 18.04.3
* Node v12.14.1
* Android

And it works correctly.

---------

Can I please for debug it in context of expo snack tool?

**Comment by palingheorghe** [comment]
Hi @gustawdaniel ! 
Thank you for being interested in our products! Expo Snack usually only accepts certain libraries and it might be that one of the libraries (most probably galio-framework) is not compatible with Expo Snack at the moment. 

Thanks,
Alin
