### ISSUE TITLE
Account screen is cropped

### ISSUE THREAD

**Issue by bozzmob** [creativetimofficial/argon-react-native#16]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

## Steps to Reproduce

Open the app, navigate to Account from the left navigation bar.

## Context
The UI is cropped at the bottom, it is not as intended.

* Device: Samsung Galaxy S7 Edge
* Operating System: Android
* Browser and Version: N/A

![photo_2020-02-13_12-59-28](https://user-images.githubusercontent.com/1252941/74411210-bd6bb180-4e60-11ea-9b36-5a6103636880.jpg)

**Comment by palingheorghe** [comment]
Hi @bozzmob ! Thank you for being interested in our product! Unfortunately, you'll have to re-design this screen so it could fit on your screen-size.  You could also make the card bigger by going into the `Register.js` file. At the bottom of the file you'll find the `styles` object. You'll have to modify the `height` style from `registerContainer`. You could go something like this: `height: height * 0.85`. I think this will be big enough for all the elements. 

Thanks,
Alin
