### ISSUE TITLE
Using with version expo 36

### ISSUE THREAD

**Issue by DanielNugent** [creativetimofficial/argon-react-native#18]
# Expected Behavior
The expo client starts properly

Please describe the behavior you are expecting

# Current Behavior
The client crashes

What is the current behavior?

# Failure Information (for bugs)

expo start
Starting project at D:\Downloads\argon-react-native-master\argon-react-native-master
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
error Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class.

Metro Bundler process exited with code 1
Set EXPO_DEBUG=true in your env to view the stack trace.

## Steps to Reproduce

Have version 36 of the expo cli installed. 

## Context

* Device: PC
* Operating System: W10
* Browser and Version: Chrome

expo start
Starting project at D:\Downloads\argon-react-native-master\argon-react-native-master
Expo DevTools is running at http://localhost:19002
Opening DevTools in the browser... (press shift-d to disable)
error Invalid regular expression: /(.*\\__fixtures__\\.*|node_modules[\\\]react[\\\]dist[\\\].*|website\\node_modules\\.*|heapCapture\\bundle\.js|.*\\__tests__\\.*)$/: Unterminated character class.

Metro Bundler process exited with code 1
Set EXPO_DEBUG=true in your env to view the stack trace.

**Comment by palingheorghe** [comment]
Hi @DanielNugent ! Thank you for your interest in our products! You can find out more about this error here: https://github.com/facebook/react-native/issues/26969 . This is an issue with react-native/node version and not with our app. I suggest to reinstall the product with a clear cache first and then try fixing the issue. 

Thanks,
Alin
