### ISSUE TITLE
Only an empty screen is rendered

### ISSUE THREAD

**Issue by jantobola** [creativetimofficial/argon-react-native#19]
# Prerequisites

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

`expo start` and scanning the QR should show some UI.

# Current Behavior

I did the following:
1. `yarn global add expo-cli`
2. `yarn install`
3. `expo start`
4. Scan the QR with Expo or click "run on Android device" in web UI.
5. It showed an empty screen on my android device. Nothing else happened.

# Failure Information (for bugs)

No errors printed.

> INFO
13:08
Starting Metro Bundler on port 19001.
INFO
13:08
Successfully ran `adb reverse`. Localhost URLs should work on the connected Android device.
INFO
13:08
Tunnel ready.
INFO
13:08
Opening on Android device

## Steps to Reproduce

1. `yarn global add expo-cli`
2. `yarn install`
3. `expo start`
4. Scan the QR with Expo or click "run on Android device" in web UI.

## Context

* Device: OnePlus 7 Pro
* Operating System: Linux Manjaro
* Browser and Version: Chrome Version 77.0.3865.120 (Official Build) (64-bit)

## Failure Logs

None

**Comment by jantobola** [comment]
I had to add 'react-native-screens' and clear cache to get it working.

**Comment by palingheorghe** [comment]
Hi @jantobola ,

Thank you for being interested in our products! We are now working to update the `Argon React Native` product to `react-navigation@v5` which will solve all of these new issues people are encountering.
Thank you for your patience! 

Alin🧜🏽‍♂️

**Comment by ishan28mkip** [comment]
Having the same issue. Issue fixed if I install react-native-screens.

**Comment by palingheorghe** [comment]
The app has been updated to v1.4.0, you can find out more about the changes here: https://github.com/creativetimofficial/argon-react-native/releases . This solves the issue you've described. Thank you for your feedback.

Alin
