### ISSUE TITLE
Setting the web or ios env

### ISSUE THREAD

**Issue by Mikeez** [creativetimofficial/argon-react-native#25]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ X] I am running the latest version
- [X ] I checked the documentation and found no answer
- [ X] I checked to make sure that this issue has not already been filed
- [ X] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Running Argon on the browser

# Current Behavior

I am getting a few errors

```ERROR
12:48
 web  Failed to compile.
C:/Users/Mikeez/Desktop/Project/argon-react-native-master/argon-react-native-master/node_modules/react-native-modal-dropdown/components/ModalDropdown.js
Module not found: Can't resolve 'react-native-web/dist/exports/ActivityIndicator' in 'C:\Users\Mikeez\Desktop\Project\argon-react-native-master\argon-react-native-master\node_modules\react-native-modal-dropdown\components'```

# Failure Information (for bugs)

The webpage is blank and if I inspect I see: ```Uncaught SyntaxError: Unexpected token '!'

```

## Steps to Reproduce

1. npm install
2. npm start (expo installed, expo start)

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: Computer and iPhone
* Operating System: Windows 10 and iOS
* Browser and Version: Chrome latest, iOS latest

I believe I have issue setting it up, setting the development environment. What am I missing?

**Comment by sirramin** [comment]
I have the same issue.

**Comment by hetmann** [comment]
@sirramin @Mikeez use the latest version :) it has a lot of fixes.
