### ISSUE TITLE
Issue starting up project locally

### ISSUE THREAD

**Issue by cooperhurt** [creativetimofficial/argon-react-native#26]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

For some reason when trying to compile master branch locally it will not compile and gives the following error:
`Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s, 
a useEffect cleanup function,
    in Unknown (at withExpoRoot.js:22)`

# Current Behavior

What is the current behavior?
Gives the error listed above

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Checkout master
2. npm i
3. npm start android

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

Appears to be happening on all of the devices I try it on.

## Failure Logs

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in %s.%s, 
a useEffect cleanup function,
    in Unknown (at withExpoRoot.js:22)
- node_modules\react-native\Libraries\YellowBox\YellowBox.js:63:8 in console.error
- node_modules\expo\build\environment\muteWarnings.fx.js:27:24 in error
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:645:36 in warningWithoutStack
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:20432:6 in warnAboutUpdateOnUnmountedFiberInDEV
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:18518:41 in scheduleUpdateOnFiber
- node_modules\react-native\Libraries\Renderer\implementations\ReactNativeRenderer-dev.js:11484:17 in dispatchAction
* [native code]:null in dispatchAction
```

**Comment by arialblack14** [comment]
@cooperhurt Have you solved this?
I am facing the same issue and all solutions I have tried cause other problems....

**Comment by olagon** [comment]
Same here

**Comment by matteosantini** [comment]
I found a fix for this issue.
Try with this:
Go to App.js and delete the current rows:
from 60 to 68 and the curly bracket in line 78.

I hope it works for you!

![image](https://user-images.githubusercontent.com/62031271/94912184-91f90e00-04a7-11eb-8fa6-3c0f0e3a49ea.png)

**Comment by ericluwj** [comment]
This is a very obvious bug, because the condition whereby `isLoadingComplete=true` and `fontsLoaded=false` is not catered for.

Just remove `else if(fontsLoaded)`:

```
  if(!fontsLoaded && !isLoadingComplete) {
    return (
      <AppLoading
        startAsync={_loadResourcesAsync}
        onError={_handleLoadingError}
        onFinish={_handleFinishLoading}
      />
    );
  } else {
    return (
      <NavigationContainer>
        <GalioProvider theme={argonTheme}>
          <Block flex>
            <Screens />
          </Block>
        </GalioProvider>
      </NavigationContainer>
    );
  }
```
