### ISSUE TITLE
Error ./Link not resolved on initial startup

### ISSUE THREAD

**Issue by devotb** [creativetimofficial/argon-react-native#27]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Initial project to load properly

# Current Behavior

Error is thrown: Unable to resolve "./Link" from "node_modules/@react-navigation/native/src/index.tsx"
Failed building JavaScript bundle.

I tried downgrading react-gesture-handler, react-navigation, but no luck

# Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Clone repo
2. npm i
3. npm start

## Context

package.json after install
{
  "name": "argon-react-native",
  "version": "1.5.0",
  "description": "Argon React Native, based on Argon Design System. Coded by Creative Tim",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "eject": "expo eject"
  },
  "repository": {
    "type": "git",
    "url": "git+https://github.com/creativetimofficial/argon-react-native.git"
  },
  "dependencies": {
    "@react-native-community/masked-view": "0.1.6",
    "@react-navigation/bottom-tabs": "^5.0.6",
    "@react-navigation/compat": "^5.0.0",
    "@react-navigation/drawer": "5.0.0",
    "@react-navigation/native": "5.0.0",
    "@react-navigation/stack": "5.0.0",
    "@use-expo/font": "^2.0.0",
    "expo": "^37.0.0",
    "expo-asset": "~8.1.5",
    "expo-font": "~8.1.0",
    "galio-framework": "^0.6.3",
    "prop-types": "^15.7.2",
    "react": "16.9.0",
    "react-native": "https://github.com/expo/react-native/archive/sdk-37.0.1.tar.gz",
    "react-native-gesture-handler": "~1.6.0",
    "react-native-modal-dropdown": "^0.7.0",
    "react-native-reanimated": "~1.7.0",
    "react-native-safe-area-context": "0.7.3",
    "react-native-screens": "~2.2.0"
  },
  "devDependencies": {
    "babel-preset-expo": "^8.2.1"
  },
  "keywords": [
    "argon react native",
    "argon design system",
    "argon app react native",
    "argon iOS",
    "react native iOS",
    "creative tim",
    "argon Android",
    "react native ui kit",
    "react native expo",
    "freebie",
    "react native argon design",
    "react native galio",
    "galio argon free",
    "galio react native free app",
    "argon expo react native",
    "react native ui template"
  ],
  "author": "Creative Tim <hello@creative-tim.com> (https://www.creative-tim.com/)",
  "license": "MIT",
  "bugs": {
    "url": "https://github.com/creativetimofficial/argon-react-native/issues"
  },
  "homepage": "https://demos.creative-tim.com/argon-react-native"
}
## Failure Logs

Please include any relevant log snippets or files here.

**Comment by hetmann** [comment]
@devotb please use the latest version :) it has a lot of fixes.
