### ISSUE TITLE
Duplicate resource error with signed bundle generation - Android Studio

### ISSUE THREAD

**Issue by Milan991** [creativetimofficial/argon-react-native#28]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ ] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Successful generation of signed bundle in Android Studio. 

# Current Behavior

Getting the "Duplicate resource" error for `assets_config_argon.json` and `assets_config_argon.ttf`.

# Failure Information (for bugs)

> :app:mergeReleaseResources 2 errors
> 
> app/build/generated/res/react/release/raw/assets_config_argon.json
> Duplicate resource
> 
> app/build/generated/res/react/release/raw/assets_config_argon.ttf
> Duplicate resource

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Device: Huawei Mate 10 Lite
* Operating System: Android

**Comment by geekytushar** [comment]
Delete everything in these 2 folders-

    android\app\src\main\res\raw\
    android\app\build\generated\res\react\release\raw\

then run

```
cd android
./gradlew assembleRelease
```

**Comment by Milan991** [comment]
Thank you. That has solved the issue.
