### ISSUE TITLE
cant run argon-react-native have issues

### ISSUE THREAD

**Issue by vitaly87** [creativetimofficial/argon-react-native#35]
I am trying to use argon-react-native
the issue that it have a lot of issues on start

Cannot read property 'style' of undefined
Module.../../../../../../../../../..//node_modules/galio-framework/src/Toast.js

**Comment by hetmann** [comment]
@vitaly87 try installing the latest version of `galio-framework` using npm or yarn 
```sh
yarn install galio-framework@latest
```
