### ISSUE TITLE
Error 'Unexpected token' on static keyword

### ISSUE THREAD

**Issue by sergous** [creativetimofficial/argon-react-native#37]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest version
- [x] I checked the documentation and found no answer
- [x] I checked to make sure that this issue has not already been filed
- [x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Install and run correctly

# Current Behavior

Then I run the command:
```
expo start web
```
I can see the compile error below.

# Failure Information (for bugs)

```
Failed to compile.
/Users/sergous/Development/ReactNative/argon-pro-react-native-v1.6.0/node_modules/galio-framework/src/Toast.js 11:19
Module parse failed: Unexpected token (11:19)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| 
| class Toast extends Component {
>   static propTypes = {
|     children: PropTypes.node.isRequired,
|     isShow: PropTypes.bool.isRequired,
```

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. yarn install
2. expo start
3. get error

## Context

The current workaround is replacing 
```
import 'galio-framework'
```
with symlink:
```
ln -s node_modules/galio-framework/src galio-framework
```

* Device: Mac
* Operating System: OS X 11.4
* Browser and Version: Chrome

## Failure Logs

Please include any relevant log snippets or files here.

**Comment by hetmann** [comment]
@sergous Currently the `galio-framework` doesn't have support for react-native-web.

**Comment by sergous** [comment]
What does it mean - I cannot start the argon-react-native in the browser?
When this support can be added?

**Comment by hetmann** [comment]
> What does it mean - I cannot start the argon-react-native in the browser?
> When this support can be added?

Exactly, you cannot user argon-react-native in the browser. We currently don't have a date when this will be added.

**Comment by sergous** [comment]
Thanks for reply Hermann!
