### ISSUE TITLE
want to separate onboarding screen and other screens

### ISSUE THREAD

**Issue by AkashThoriya** [creativetimofficial/argon-react-native#5]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ yes] I am running the latest version
- [yes ] I checked the documentation and found no answer
- [yes ] I checked to make sure that this issue has not already been filed
- [ yes] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

want to separate onboarding screen and other screens because I don't want drawer menu on onboarding screen.

# Current Behavior

do not able to do that

#i am just beginner and trying hard to learn to react native and I am waiting for Pro version

**Comment by palingheorghe** [comment]
Hi, 
The best help you can get regarding this issue is from https://reactnavigation.org/ . This is the library we're using for our product's navigation. You would have to create another stack for the onboarding and place that as the first screen in your stack of screens. 

Alin 🧜🏽‍♂️
