### ISSUE TITLE
Error while running through expo

### ISSUE THREAD

**Issue by Gardens18** [creativetimofficial/argon-react-native#6]
Freshly downloaded and installed today, getting the below error when we execute through expo in IOS simulator 

**null is not an object (evaluating 'null.isRequired') <unknown> Icon.js:48:13 loadModuleImplementation require.js:292:12 <unknown> index.js:5 loadModuleImplementation require.js:292:12 <unknown> App.js:4 loadModuleImplementation require.js:292:12 <unknown> AppEntry.js:2 loadModuleImplementation require.js:292:12 guardedLoadModule require.js:179:45 global code <unknown file>:0**

**Comment by palingheorghe** [comment]
Updated the app for v1.2.0. Please reopen the issue if you still encounter the same problem.
