### ISSUE TITLE
.../node_modules\galio-framework\src\Text.js: Argument name clash (24:2)

### ISSUE THREAD

**Issue by procarrera** [creativetimofficial/argon-react-native#9]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x ] I am running the latest version
- [x ] I checked the documentation and found no answer
- [ x] I checked to make sure that this issue has not already been filed
- [ x] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior
**Bundle my teste app**
I have downloaded the last version of Argon-React-Native from your website, runned yarn install to get all updated dependencies, runned yarn start, which starter expo start subsequently.

# Current Behavior
After scan the QR Code into my Expo app installed on a Android with specs below, the code start running to Build a JavaScript bundle, but then the compilation crashes with failure below.

# Failure Information (for bugs)
```
Error: C:\node\argo\node_modules\galio-framework\src\Text.js: Argument name clash (24:2)

  22 |   center,
  23 |   children,
> 24 |   style,
     |   ^
  25 |   styles,
  26 |   theme,
  27 |   ...rest
Failed building JavaScript bundle.
events.js:174
```

## Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. Download last version of Argon direct from site
2. go to the directory and run yard install
3. run yard start
4. scan the QR code and open in your mobile

## Context
I am very new to Android development, but I believe it shouldnt be an erro as i am not changing anything and i am trying to follow all steps.

* Device:
node v10.16.3
npm  v6.9.0
argon-react-native@1.2.0
expo 3.3.0

## Failure Logs

Please include any relevant log snippets or files here.
[2019-10-15T02_57_17_839Z-debug.log](https://github.com/creativetimofficial/argon-react-native/files/3727246/2019-10-15T02_57_17_839Z-debug.log)

![Capturar](https://user-images.githubusercontent.com/53456120/66798459-68d11d80-eee4-11e9-8717-7b553d567ddf.PNG)

**Comment by blueplanet** [comment]
I had the same problem

**Comment by blueplanet** [comment]
@procarrera @palingheorghe 
After upgrade galio to v0.6.3, it worked fine.

https://github.com/galio-org/galio/issues/140

**Comment by procarrera** [comment]
Nice. worked for me!
Tks
@blueplanet @palingheorghe
